// ============================================================
// KN WORKS — CONTENT DATA
// Edit this file to update site content.
// ============================================================

const KN = {

  // ---- Site meta -------------------------------------------
  site: {
    name: 'Kyle Numann',
    tagline: 'Sound, image, Nashville TN.',
    location: 'Nashville, TN',
    email: 'kyle.numann@gmail.com',
    instagram: 'kylenumann',
    bandcamp: 'https://infinitelimb.bandcamp.com',
    copyright: '2026',
  },

  // ---- Home ------------------------------------------------
  home: {
    heroImage: 'assets/images/kyle-hero.jpg',
    heroAlt: 'Kyle Numann',
    bio: `Ambient/experimental music as <a href="https://infinitelimb.bandcamp.com">Infinite Limb</a>. Monthly series <a href="https://instagram.com/ambient_sundays">Ambient Sundays</a>. Guitar in <a href="https://cloudmouthmusic.com">Cloudmouth</a> (2012–2024). Illustration, print, visual work.`,
    links: [
      { label: 'Bandcamp', url: 'https://kylenumann.bandcamp.com' },
      { label: 'Instagram', url: 'https://instagram.com/kylenumann' },
      { label: 'Cloudmouth', url: 'https://cloudmouthmusic.com' },
    ],
    // Titles must match entries in music.releases
    featuredReleases: [
      'Drums and Drones: Live at Trinity Community Commons',
      'Drones 01: Lush Pools',
      'Dark Energy',
    ],
  },

  // ---- Music -----------------------------------------------
  music: {
    intro: 'Recorded output. Multiple projects, 2012–present.',
    releases: [
      {
        artist: 'Infinite Limb',
        title: 'Drums and Drones: Live at Trinity Community Commons',
        year: 2025,
        type: 'Album',
        description: 'Organic vocal and synthesizer drones paired with a percussion ensemble. Recorded live in a burnt-out church in East Nashville.',
        cover: 'assets/images/covers/drums-and-drones.jpg',
        bandcamp: 'https://infinitelimb.bandcamp.com/album/drums-and-drones-live-at-trinity-community-commons',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=3534046052/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://infinitelimb.bandcamp.com/album/drums-and-drones-live-at-trinity-community-commons">Drums and Drones: Live at Trinity Community Commons by Infinite Limb</a></iframe>',
      },
      {
        artist: 'SPKN',
        title: 'SPKN EP1',
        year: 2024,
        type: 'EP',
        description: 'Collaborative project with Steve Poulton (Altered Statesman) and numerous area musicians.',
        cover: 'assets/images/covers/spkn-ep1.jpg',
        bandcamp: 'https://spknmusic.bandcamp.com/album/spkn-ep1',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=2088887294/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://spknmusic.bandcamp.com/album/spkn-ep1">SPKN EP1 by SPKN</a></iframe>',
      },
      {
        artist: 'Infinite Limb',
        title: 'Drones 01: Lush Pools',
        year: 2023,
        type: 'Album',
        description: 'Four deep, lush, long-form sound environments that move slowly through their worlds. Organic drone in four colors.',
        cover: 'assets/images/covers/drones-01-lush-pools.jpg',
        bandcamp: 'https://infinitelimb.bandcamp.com/album/drones-01-lush-pools',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=1914765862/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://infinitelimb.bandcamp.com/album/drones-01-lush-pools">Drones 01: Lush Pools by Infinite Limb</a></iframe>',
      },
      {
        artist: 'Cloudmouth',
        title: 'Take Me To A Lake',
        year: 2022,
        type: 'Single',
        description: 'A secular hymn by way of ballad turned rock barnstormer turned ambient waterscape. The conservation of matter, the persistence of energy, myth-making, form and formlessness.',
        cover: 'assets/images/covers/take-me-to-a-lake.jpg',
        bandcamp: 'https://cloudmouthmusic.bandcamp.com/track/take-me-to-a-lake',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/track=1012131820/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://cloudmouthmusic.bandcamp.com/track/take-me-to-a-lake">Take Me To A Lake by Cloudmouth</a></iframe>',
      },
      {
        artist: 'Infinite Limb',
        title: 'Branch, Commit',
        year: 2019,
        type: 'Album',
        description: 'Instrumental polyrhythmic rock, swamp groove, organic drone, and post-blues ambiance. Electric guitar, synthesizer, accordions, banjo, suitcases, boxes of nails, and a 25-track xylophone arrangement.',
        cover: 'assets/images/covers/branch-commit.jpg',
        bandcamp: 'https://infinitelimb.bandcamp.com/album/branch-commit',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=3794019715/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://infinitelimb.bandcamp.com/album/branch-commit">Branch, Commit by Infinite Limb</a></iframe>',
      },
      {
        artist: 'Cloudmouth',
        title: 'Dark Energy',
        year: 2018,
        type: 'Album',
        description: 'Personal care, worldly terror, overwhelming contentment, and technological paranoia.',
        cover: 'assets/images/covers/dark-energy.jpg',
        bandcamp: 'https://cloudmouthmusic.bandcamp.com/album/dark-energy',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=2885908606/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://cloudmouthmusic.bandcamp.com/album/dark-energy">Dark Energy by Cloudmouth</a></iframe>',
      },
      {
        artist: 'Cloudmouth',
        title: 'Drunk On What I Am',
        year: 2016,
        type: 'Album',
        description: 'A portrait in time. The Cloudmouth live set from year one, tracked live to tape at Strangebird Recording. Band re-imaginings of earlier solo material. Out on Yeah Definitely Records.',
        cover: 'assets/images/covers/drunk-on-what-i-am-cloudmouth.jpg',
        bandcamp: 'https://cloudmouthmusic.bandcamp.com/album/drunk-on-what-i-am',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=25046862/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://cloudmouthmusic.bandcamp.com/album/drunk-on-what-i-am">Drunk On What I Am by Cloudmouth</a></iframe>',
      },
      {
        artist: 'Kyle Numann',
        title: 'Drunk On What I Am',
        year: 2014,
        type: 'Album',
        description: 'Composed song forms and experimental sound combination. Personal introspection, heartache, doubt and longing, strength and resolution. Guitar, accordion, trumpet, whiskey barrel, suitcase, chains, lumber.',
        cover: 'assets/images/covers/drunk-on-what-i-am-solo.jpg',
        bandcamp: 'https://kylenumann.bandcamp.com/album/drunk-on-what-i-am',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=3563555234/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://kylenumann.bandcamp.com/album/drunk-on-what-i-am">Drunk On What I Am by Kyle Numann</a></iframe>',
      },
      {
        artist: 'Kyle Numann',
        title: 'Ukulalia',
        year: 2012,
        type: 'Album',
        description: 'Songs written along the West Coast in 2008. Ukulele, guitars, trumpet, accordion, bike spokes, silverware, sword, and other assorted sounds.',
        cover: 'assets/images/covers/ukulalia.jpg',
        bandcamp: 'https://kylenumann.bandcamp.com/album/ukulalia',
        embed: '<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/album=3624093064/size=large/bgcol=ffffff/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://kylenumann.bandcamp.com/album/ukulalia">Ukulalia by Kyle Numann</a></iframe>',
      },
    ],
    projects: [
      {
        name: 'Cloudmouth',
        url: 'https://cloudmouthmusic.com',
        bandcamp: 'https://cloudmouthmusic.bandcamp.com',
        description: 'Avant folk · Nashville · 2012–2024. Songwriter, guitarist, vocalist, producer.',
      },
      {
        name: 'Infinite Limb',
        url: 'https://infinitelimb.bandcamp.com',
        bandcamp: 'https://infinitelimb.bandcamp.com',
        description: 'Experimental / ambient / drone.',
      },
      {
        name: 'SPKN',
        url: 'https://spknmusic.bandcamp.com',
        bandcamp: 'https://spknmusic.bandcamp.com',
        description: 'Collaborative project w/ Steve Poulton (Altered Statesman).',
      },
      {
        name: 'Ambient Sundays',
        url: 'https://instagram.com/ambient_sundays',
        bandcamp: 'https://instagram.com/ambient_sundays',
        description: 'Monthly ambient series · Nashville.',
      },
    ],
  },

  // ---- Live ------------------------------------------------
  live: {
    intro: 'Performance log.',
    ambientSundays: {
      name: 'Ambient Sundays',
      description: 'Monthly ambient series. Nashville, TN. Quiet listening, improvised sound.',
      url: 'https://instagram.com/ambient_sundays',
      instagram: 'https://instagram.com/ambientsundays',
    },
    shows: [
      // Upcoming shows — add here:
      // { date: '2026-04-20', venue: 'Venue Name', location: 'Nashville, TN', project: 'Infinite Limb', url: '' },
    ],
    pastShows: [
      { date: '2026-02-21', venue: 'New Media Nashville Gathering', location: 'Nashville, TN', project: 'Infinite Limb', url: 'https://www.instagram.com/p/DU1g8-7kdXm/' },
      // Infinite Limb at Ambient Sundays — Rice Vice, Nashville
      { date: '2025-12-14', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: 'https://www.instagram.com/ambient_sundays/' },
      { date: '2025-11-09', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: 'https://www.instagram.com/ambient_sundays/' },
      { date: '2025-10-12', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: 'https://www.instagram.com/ambient_sundays/' },
      { date: '2025-09-14', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: '' },
      { date: '2025-08-31', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: '' },
      { date: '2025-07-27', venue: 'Rice Vice', location: 'Nashville, TN', project: 'Infinite Limb', note: 'Ambient Sundays', url: '' },
      // Cloudmouth
      { date: '2024-10-16', venue: 'The 5 Spot', location: 'Nashville, TN', project: 'Cloudmouth', url: '' },
      { date: '2024-06-25', venue: 'The Cobra', location: 'Nashville, TN', project: 'Cloudmouth', url: '' },
      { date: '2024-06-14', venue: 'Punk Wok', location: 'Nashville, TN', project: 'Cloudmouth', url: '' },
    ],
  },

  // ---- Video -----------------------------------------------
  video: {
    intro: 'Directed and produced. 2016–present.',
    videos: [
      {
        title: 'Take Me To A Lake',
        artist: 'Cloudmouth',
        year: 2024,
        youtubeId: 'GWIsYyxvdhQ',
      },
      {
        title: 'Ground Holds Water',
        artist: 'Infinite Limb',
        year: 2018,
        youtubeId: 'DyCbUY0N7LM',
      },
      {
        title: 'Nice Looking Mountain',
        artist: 'Cloudmouth',
        year: 2018,
        youtubeId: 'ere2qsctSls',
      },
      {
        title: 'Drunk On What',
        artist: 'Cloudmouth',
        year: 2017,
        youtubeId: 'wrtgR7srYXI',
      },
      {
        title: 'Little House',
        artist: 'Cloudmouth',
        year: 2016,
        youtubeId: 'IdyAyWjqYFg',
      },
    ],
  },

  // ---- Art -------------------------------------------------
  art: {
    intro: 'Illustration, print, design. 2012–present.',
    collections: [
      {
        slug: 'venue-illustrations',
        title: 'Venue Illustrations',
        description: 'An ongoing series re-imagining Nashville\'s storied live music venues — alternate locations, radical situations, stylized presentation.',
      },
      {
        slug: 'music-designs',
        title: 'Music Designs',
        description: 'Artwork and design work for music projects.',
      },
    ],
    pieces: [
      // ---- Venue Illustrations collection ----
      {
        slug: 'crack-mammoth-basement',
        title: 'The Basement',
        year: 2016,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/Crack-Mammoth-The-Basement-7-2016-v2.jpg'],
        description: 'The Basement, Nashville TN. Made for a Crack Mammoth show, 2016.',
      },
      {
        slug: '5-spot',
        title: 'The 5 Spot',
        year: 2016,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/5-Spot-v3-art.jpg'],
        description: 'The 5 Spot, East Nashville TN. Made for a Crack Mammoth show.',
      },
      {
        slug: 'the-end',
        title: 'The End',
        year: 2016,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/Officially-Altered-at-The-End-No-Text.jpg'],
        description: 'The End, Nashville TN. A long-standing venue on Elliston Place, being engulfed in Nashville\'s new skyline.',
      },
      {
        slug: 'springwater-poster',
        title: 'The Springwater',
        year: 2016,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/Springwater-Night-Woods-Poster.jpg'],
        description: 'Re-imagining of Nashville\'s most iconic dive bar into a secluded cabin under a star-splattered sky.',
      },
      {
        slug: 'cloudmouth-charlie-bobs',
        title: 'Charlie Bob\'s',
        year: 2017,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/Cloudmouth-2017-4-12-Charlie-Bobs-no-text.jpg'],
        description: 'Cloudmouth show poster, April 2017.',
      },
      {
        slug: 'crack-mammoth-tower',
        title: 'Tower Defense',
        year: 2016,
        type: ['Illustration'],
        collection: 'venue-illustrations',
        images: ['assets/images/art/Crack-Mammoth-Tower-Defense-v02.jpg'],
        description: '',
      },
      // ---- Music Designs collection ----
      {
        slug: 'cloudmouth-album-art',
        title: 'Cloudmouth Album Art',
        year: 2017,
        type: ['Illustration', 'Print'],
        collection: 'music-designs',
        images: [
          'assets/images/art/Drunk-On-What-Cover.jpg',
          'assets/images/art/Drunk-On-What-On-Page-Sleeve-v3.jpg',
        ],
        description: 'Album art for Cloudmouth\'s first release, Drunk On What I Am. Each physical copy came with a fold-out 8×11 poster.',
      },
      {
        slug: 'springwater-cabin-poster',
        title: 'Springwater Cabin Poster',
        year: 2014,
        type: ['Illustration', 'Print'],
        collection: 'music-designs',
        images: [
          'assets/images/art/2014-12-18-Springwater-Print.jpg',
          'assets/images/art/Springwater-Night-Woods-Poster-e1420739284621.jpg',
        ],
        description: 'Poster illustration for a show of local songwriters at Nashville\'s most infamous dive bar, Springwater.',
      },
      {
        slug: 'listening-party',
        title: 'Listening Party',
        year: 2017,
        type: ['Illustration', 'Print'],
        collection: 'music-designs',
        images: ['assets/images/art/The-Post-Listening-Party-i04.jpg'],
        description: 'Poster illustration for a show at the local coffee shop/juice bar/music venue The Post.',
      },
      {
        slug: 'drunk-on-what-i-am',
        title: 'Drunk On What I Am',
        year: 2014,
        type: ['Illustration'],
        collection: 'music-designs',
        images: [
          'assets/images/art/Drunk-on-Poster.jpg',
          'assets/images/art/drunk-on-what-sketches.jpg',
          'assets/images/art/drunk-on-what-sketches-02.jpg',
        ],
        description: 'Exploring cover concepts for the album — a self-portrait meets symbolic setting. The lake-sitting-skeleton-reflection.',
      },
      {
        slug: 'squirrels',
        title: 'Squirrels Are Stealing My Tomatoes',
        year: 2014,
        type: ['Illustration', 'Print'],
        collection: 'music-designs',
        images: ['assets/images/art/Squirrels-Cover.jpg'],
        description: 'Cover illustration for Lazy Susan and the Dumbwaiters\' first album.',
      },
      {
        slug: 'captains-lurch',
        title: 'Captain\'s Lurch',
        year: 2014,
        type: ['Illustration', 'Print', 'Apparel'],
        collection: 'music-designs',
        images: [
          'assets/images/art/captains-lurch-colored.jpg',
          'assets/images/art/drunken-captain.jpg',
        ],
        description: 'Shirt design for punk rockers Muddy Rails.',
      },
      {
        slug: 'volunteer-gardners-brigade',
        title: 'Volunteer Gardners Brigade',
        year: 2014,
        type: ['Illustration', 'Logos'],
        images: [
          'assets/images/art/VGB-Poster-11x17.jpg',
          'assets/images/art/VGB-sketches-full2.jpg',
        ],
        description: 'Badge-style logo and illustrated poster for a local sustainable food initiative, styled after WWII-era Victory Garden posters.',
      },
      {
        slug: 'olmec-records',
        title: 'Olmec Records',
        year: 2013,
        type: ['Illustration', 'Print', 'Logos'],
        collection: 'music-designs',
        images: [
          'assets/images/art/olmec_pyramidhead_color_sm.jpg',
          'assets/images/art/olmec_head_logo_textured.jpg',
          'assets/images/art/headsketch2.jpg',
        ],
        description: 'Nashville-based collaborative hip-hop group. Identity and artwork using iconic imagery from South American anthropology.',
      },
      {
        slug: 'the-grayces-shirt',
        title: 'The Grayces Shirt',
        year: 2012,
        type: ['Illustration', 'Print', 'Apparel'],
        collection: 'music-designs',
        images: [
          'assets/images/art/shirt_octocar.jpg',
          'assets/images/art/octo_car_final-011.jpg',
        ],
        description: 'Nashville rock trio The Grayces needed a new shirt — a deep adventure scene almost as exciting as their live show.',
      },
      {
        slug: 'muddy-rails-album',
        title: 'Muddy Rails Album',
        year: 2012,
        type: ['Illustration', 'Print', 'Logos'],
        collection: 'music-designs',
        images: [
          'assets/images/art/cover_web1.jpg',
          'assets/images/art/inside_web1.jpg',
          'assets/images/art/backcover_web.jpg',
        ],
        description: 'Album art for Iowa punk-rock group Muddy Rails. Hand-illustrated on a 2×6 board, photographed, colored and textured digitally.',
      },
      {
        slug: 'aquariums-shirt',
        title: 'Aquariums Shirt',
        year: 2012,
        type: ['Print', 'Apparel'],
        collection: 'music-designs',
        images: ['assets/images/art/aquariums-sitters-ink.jpg'],
        description: 'Shirt design for Nashville songwriter and d.i.y. folk band Aquariums.',
      },
      {
        slug: 'fancytramp',
        title: 'Fancytramp',
        year: 2012,
        type: ['Illustration', 'Print', 'Apparel'],
        collection: 'music-designs',
        images: ['assets/images/art/Fancytramp-Centaur.jpg'],
        description: 'Nashville glam-punk-dream rock band Fancytramp needed a guitar-slinging ferocious centaur mascot.',
      },
      {
        slug: 'green-wagon-bongo-java',
        title: 'Green Wagon / Bongo Java',
        year: 2012,
        type: ['Illustration', 'Print'],
        images: [
          'assets/images/art/greenwag_bongolabel_5pt1.jpg',
          'assets/images/art/greenwag_bongolabels1.jpg',
        ],
        description: 'Custom coffee labels for Bongo Java\'s roasted beans, sold at East Nashville\'s local general store The Green Wagon.',
      },
      {
        slug: '5-points-friday',
        title: '5 Points Friday',
        year: 2012,
        type: ['Print', 'Infographic', 'Logos'],
        images: [
          'assets/images/art/5points_banner_web.jpg',
          'assets/images/art/5pf_promo.jpg',
        ],
        description: 'Promotional poster, magazine ad, logo and East Nashville map design for the 5 Points Friday market.',
      },
      {
        slug: 'a-what-show',
        title: 'A What-show?',
        year: 2012,
        type: ['Print', 'Apparel'],
        collection: 'music-designs',
        images: [
          'assets/images/art/Fuckshow-Final.jpg',
          'assets/images/art/Fuckshow-Logo.jpg',
        ],
        description: 'Visceral visual imagery to match visceral music. Hand drawn and digitally colored.',
      },
      {
        slug: 'cfa-crawfish-boil',
        title: 'CFA Crawfish Boil',
        year: 2013,
        type: ['Illustration', 'Print'],
        images: [
          'assets/images/art/Crawfish-Boil-Poster.jpg',
          'assets/images/art/logo-preview.jpg',
        ],
        description: 'Poster and logo for Community Food Advocates\' Spring Crawfish Boil fundraiser.',
      },
      {
        slug: 'community-food-advocates',
        title: 'Community Food Advocates',
        year: 2012,
        type: ['Print'],
        images: [
          'assets/images/art/food-day-2012-web.jpg',
          'assets/images/art/save-the-date-web.jpg',
        ],
        description: 'Last-minute promotional poster for the Buffalo Valley Farm Dinner with vivid textures and food photography.',
      },
      {
        slug: 'new-whole-usuals-poster',
        title: 'New Whole Usuals Poster',
        year: 2012,
        type: ['Illustration', 'Print'],
        collection: 'music-designs',
        images: [
          'assets/images/art/poster_nwu.jpg',
          'assets/images/art/poster_nwu2.jpg',
        ],
        description: 'Hand-illustrated poster for The New Whole Usuals — their shows are a spectacle worthy of a Shakespearean stage.',
      },
      {
        slug: 'heritage-dance-project',
        title: 'Heritage Dance Project',
        year: 2012,
        type: ['Print', 'Logos', 'Apparel'],
        images: ['assets/images/art/Heritage-Shirt-e1344466346890.jpg'],
        description: 'Shirt design for Nashville\'s Heritage Dance Project. The dancer\'s form abstracted into the shape of branches and leaves.',
      },
      {
        slug: 'seed-money-suppers',
        title: 'Seed Money Suppers',
        year: 2013,
        type: ['Print', 'Infographic', 'Illustration'],
        images: ['assets/images/art/CFA-PTP-NATIVE-ad-revised-Small.jpg'],
        description: 'Infographic for Community Food Advocates\' micro-grant program for a healthier Nashville food system.',
      },
    ],
  },

};
